name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: '23 22 * * 5' # weekly at 22:23 (UTC) on Friday
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: OSSF Scorecard analysis
    runs-on: ubuntu-latest
    concurrency:
      group: scorecard-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      security-events: write # for Code scanning upload
      id-token: write # for publishing results with GitHub OIDC
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      # Upload the results as artifacts (optional). Commenting out will disable
      # uploads of run results in SARIF format to the repository Actions tab.
      # https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      - name: "Upload artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard (optional).
      # Commenting out will disable upload of results to your repo's Code Scanning dashboard
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@1190a975f95ce23525efb6a3fc21ea29567c1b52 # v3.38.2
        with:
          sarif_file: results.sarif
